appname: kater

server:
  port: 8764

spring:
  http:
    encoding:
      enabled: true
      charset: UTF-8
  application:
    name: kater
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.100.131.79:3306/fa_kobe2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: jxh1988
  rabbitmq:
    host: 39.100.131.79
    port: 5672
    virtual-host: /
  redis:
    database: 0
    host: 39.100.131.79
    port: 6379
    password: jxh1988
  mongo:
    host: 39.100.131.79
    port: 27017
    dbName: fit-eat
    username: jxh
    password: jxh1988
    url: ${spring.mongo.username}:${spring.mongo.password}@${spring.mongo.host}:${spring.mongo.port}/${spring.mongo.dbName}
  session:
    store-type: redis
    timeout: 3600 #seconds in used
    redis:
      flush-mode:  on-save # Sessions flush mode.
      namespace: kater # Namespace for keys used to store sessions.

redis:
  region:
    database: 5
  lettuce:
    pool:
      max-active: 8
      max-wait: 10000
      max-idle: 4
      min-idle: 0
    timeout: 1000000
    shutdown-timeout: 400

mybatis-plus:
  mapper-locations:
    classpath: mapper/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0


storage:
  file:
    path: /Users/micezhao/uploadFile/resource
    max_size: 16M

