appname: kidd

server:
  port: 8763

spring:
   http:
      encoding:
         enabled: true
         charset: UTF-8
   application:
      name: kidd
   profiles:
      include: sessiondev
   rabbitmq:
      host: 118.190.53.214
      port: 5682
      virtual-host: /
   redis:
      database: 0
      host: 118.190.53.214
      port: 16379
      password: 891122


zuul:
   routes:
      kobe-url:
         path: /kobe/**
         url: http://localhost:8764/ # 开发环境，指向本级服务
         ## serviceId: kobe
      routes:
      kobe-url:
         path: /allan/**
         url: http://localhost:8765/ # 开发环境，指向本级服务
          ## serviceId: allan
customizezuul:
   excludedPaths: /kobe/login/**
