appname: kidd

server:
   port: 8763

spring: 
   http:
      encoding:
         enabled: true
         charset: UTF-8
   application:
      name: kidd
   rabbitmq:
      host: 39.100.131.79
      port: 5672
      virtual-host: /
   redis:
      database: 0
      host: 39.100.131.79
      port: 6379
      password: jxh1988
   session:
      store-type: redis
      timeout: 3600 #seconds in used
      redis:
         flush-mode: on-save  # Sessions flush mode.
         namespace: kater # Namespace for keys used to store sessions.

zuul:
   routes:
      kobe-url:
         path: /kater/**
         ## url: http://localhost:8764/ # 开发环境，指向本级服务
         serviceId: kater
      allan-url:
         path: /allan/**
         ## url: http://localhost:8765/ # 开发环境，指向本级服务
         serviceId: allan

customizezuul:
   excludedPaths: /kater/login/**
