appname: kobe

server:
  port: 8763
    
spring:
   application:
      name: kobe
   datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://118.190.53.214:3386/fa_kobe?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 891122
   rabbitmq:
      host: 118.190.53.214
      port: 5682
      virtual-host: /
   redis:
      database: 0
      host: 118.190.53.214
      port: 16379
      password: 891122
   mongo:
      host: 118.190.53.214
      port: 27817
      dbName: fit-eat
      username: zcmac
      password: 891122
      url: ${spring.mongo.username}:${spring.mongo.password}@${spring.mongo.host}:${spring.mongo.port}/${spring.mongo.dbName}
   session:
      store-type: redis
      timeout: 360 #seconds in used
      redis:
         flush-mode: on-save  # Sessions flush mode.
         namespace: kobe # Namespace for keys used to store sessions.
         database: 5

redis:
   region:
      database: 5
   lettuce:
      pool:
         max-active: 8
         max-wait: 10000
         max-idle: 4
         min-idle: 0
         timeout: 10000
         shutdown-timeout: 400

mybatis:
   mapperLocations: classpath*:mybatis/mapper/*.xml
credential:
   wechat:
      appId: 9100aa
      appSecret: 9100bb
      urlPattern: https://api.weixin.qq.com/sns/jscode2session?appid={0}&secret={1}&js_code={2}&grant_type=authorization_code
      errtag: errcode
       
   